export const challengeConstants = {
  READALL_REQUEST: 'CHALLENGE_READALL_REQUEST',
  READALL_SUCCESS: 'CHALLENGE_READALL_SUCCESS',
  READALL_FAILURE: 'CHALLENGE_READALL_FAILURE',
  READALL_ORPHANS_REQUEST: 'CHALLENGE_READALL_ORPHANS_REQUEST',
  READALL_ORPHANS_SUCCESS: 'CHALLENGE_READALL_ORPHANS_SUCCESS',
  READALL_ORPHANS_FAILURE: 'CHALLENGE_READALL_ORPHANS_FAILURE',
  READALL_GROUPS_REQUEST: 'CHALLENGE_GROUPS_READALL_REQUEST',
  READALL_GROUPS_SUCCESS: 'CHALLENGE_GROUPS_READALL_SUCCESS',
  READALL_GROUPS_FAILURE: 'CHALLENGE_GROUPS_READALL_FAILURE'
}
