export const teamConstants = {
  READ_REQUEST: "TEAM_READ_REQUEST",
  READ_SUCCESS: "TEAM_READ_SUCCESS",
  READ_FAILURE: "TEAM_READ_FAILURE",

  READALL_REQUEST: "TEAM_READALL_REQUEST",
  READALL_SUCCESS: "TEAM_READALL_SUCCESS",
  READALL_FAILURE: "TEAM_READALL_FAILURE"
};
