export const userConstants = {
  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
  REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

  LOGOUT: 'USER_LOGOUT',

  READ_REQUEST: 'USER_READ_REQUEST',
  READ_SUCCESS: 'USER_READ_SUCCESS',
  READ_FAILURE: 'USER_READ_FAILURE',
  READALL_REQUEST: 'USER_READALL_REQUEST',
  READALL_SUCCESS: 'USER_READALL_SUCCESS',
  READALL_FAILURE: 'USER_READALL_FAILURE',
  UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'USER_UPDATE_FAILURE',
  DELETE_REQUEST: 'USER_DELETE_REQUEST',
  DELETE__SUCCESS: 'USER_DELETE_SUCCESS',
  DELETE_FAILURE: 'USER_DELETE_FAILURE',
  UPLOAD_AVATAR_REQUEST: 'UPLOAD_AVATAR_REQUEST',
  UPLOAD_AVATAR_SUCCESS: 'UPLOAD_AVATAR_SUCCESS',
  UPLOAD_AVATAR_FAILURE: 'UPLOAD_AVATAR_FAILURE',

};